- .env.tpl
- .eslintignore
- .github/workflows/test.yaml
- .gitignore
- LICENSE.md
- package-lock.json
- package.json
- services/functions/hello.js
- services/package.json
- services/test/hello.test.js
- sst.json
- stacks/api-stack.js
- stacks/index.js
- tsconfig.json
This PR adds a skeleton for SST project for w3up-api.
Details:
- added eslint with `hd-scripts` (no pretty for now)
- used npm until pnpm properly supports sst
- added a `/hello` route to have something we can deploy and guarantee seed.run is properly setup - will be removed in favour of further routes in follow up PR
- project deployed in `us-west-2`
Things to decide:
> feat: new implementation

- api/service/store/add.js
- api/service/types.ts
- api/test/service/store.test.js
This PR tidies up a bit types. Also:
-  `origin` is a Link (CID) per https://github.com/web3-storage/w3protocol/pull/160/files so updating it.
- augmented test to check Dynamo DB content was inserted
> fix: tidy up types

- api/service/store/add.js
- api/service/types.ts
- api/test/service/store.test.js
- package-lock.json
- package.json
This PR updates deps, most notably: `"@web3-storage/access": "^5.0.1"` which makes `store/add` link and size required, as well as fixes types inference
> fix: update deps

- api/package.json
- api/service/store/add.js
- api/service/store/index.js
- api/service/store/list.js
- api/service/store/remove.js
- api/service/types.ts
- api/tables/store.js
- api/test/service/store.test.js
- package-lock.json
This PR adds the remaining `store/*` handlers: list + remove.
As follow up, created issue https://github.com/web3-storage/upload-api/issues/16 to handle the cursor moving around - this needs to be updated in spec, [access](https://github.com/web3-storage/w3protocol/blob/main/packages/access/src/capabilities/store.js#L68) and upload-api
Closes #11
> feat: store star handlers

- api/test/service/store.test.js
Our tests get pretty neat using the uncanto client to invoke things.
Also clears up some naming of the various principles so it's easier to figure out who is doing what to whom.
Aims to show off in tests what our normal flow should look like when folks delegate from a space to their agent first, and then invoke things on the space as the agent with the proof of delegation.
As suggested by @alanshaw in https://github.com/web3-storage/upload-api/pull/14/files#r1023905697
License: MIT
> feat: use ucanto client for store tests

- api/tables/store.js
make pattern consistent with other methods in the file. Doing it this way lets automagically get the params type and can explore it from our editors.
License: MIT
> refactor: capture cmd instead of params for dynamo

- api/functions/ucan-invocation-router.js
- api/package.json
- api/service/index.js
- api/service/types.ts
- api/service/upload/add.js
- api/service/upload/index.js
- api/service/upload/list.js
- api/service/upload/remove.js
- api/tables/upload.js
- api/test/fixtures.js
- api/test/helpers/context.js
- api/test/helpers/random.js
- api/test/helpers/ucanto.js
- api/test/service/store.test.js
- api/test/service/upload.test.js
- package-lock.json
- stacks/api-stack.js
This PR adds `upload/*` handlers as well as their tests.
It includes
- new Table resource with upload listing (follows same schema as w3up)
- uploadTable abstraction like storeTable
- update access to fix `upload/add` type inference
- random car helper function stolen from client tests
- updated `store` tests to use `createSpace` and `getClientConnection` helpers
Note that:
- pagination will be handled as follow up
- removes unused fixtures folder
- dynamoDB does not support deleting items without providing entire key.
- Upload table key is `primaryIndex: { partitionKey: 'uploaderDID', sortKey: 'sk' }` to be unique. However, when `upload/remove` is triggered we receive `uploaderDID` and `dataCID` and have no way to get `sk` ('dataCID#carCID'). 
- We need to perform an initial query to get …
> feat: upload star handlers

- .env.tpl
- stacks/api-stack.js
- stacks/config.js
Adds custom domain config to api definition per https://docs.sst.dev/constructs/Api#customdomain
Adds `HOSTED_ZONE` env var. the value should match a hosted zone configured in route53 that your aws account has access to.
License: MIT
> feat: deploy to custom domain up.web3.storage

- api/functions/get.js
- api/package.json
- package-lock.json
- package.json
- stacks/api-stack.js
- stacks/config.js
Adds handlers for `GET /` and `GET /version`.
`GET /` is `text/plain` for humans
```bash
❯ curl https://pr32.up.web3.storage
⁂ upload-api v3.0.0 (pr32)
- https://github.com/web3-storage/upload-api
- did:key:z6MkrZ1r5XBFZjBU34qyD8fueMbMRkKw17BZaq2ivKFjnz2z
```
`GET /version` is `application/json` for robots
```bash
❯ curl https://pr32.up.web3.storage/version -s | jq
{
"name": "@web3-storage/upload-api",
"version": "3.0.0",
"did": "did:key:z6MkrZ1r5XBFZjBU34qyD8fueMbMRkKw17BZaq2ivKFjnz2z",
"repo": "https://github.com/web3-storage/upload-api",
"commit": "0ec7b1099a99adf338f81842686cd2c88f6f449b",
"env": "pr32"
}
```
License: MIT
> feat: add GET / and /version handlers

- api/tables/store.js
- api/test/service/store.test.js
Not includes origin property with empty string value on `store/list` per https://github.com/web3-storage/upload-api/issues/16#issuecomment-1318405985
> fix: omit origin if empty on store list

- README.md
- api/access.js
- api/buckets/car-store.js
- api/functions/ucan-invocation-router.js
- api/package.json
- api/service/store/add.js
- api/service/types.ts
- api/tables/store.js
- api/test/helpers/ucanto.js
- api/test/service/store.test.js
- api/test/service/upload.test.js
- api/test/utils.js
- package-lock.json
- package.json
This PR adds a request to w3access when a `store/add` invocation is handled.
The request to w3access ensures that the target space has been verified by a user via email.
> feat: validate store/add access

- api/tables/store.js
- api/test/helpers/context.js
- api/test/helpers/ucanto.js
- api/test/service/store.test.js
- api/test/service/upload.test.js
- api/test/utils.js
Restructure tests to start containers (DynamoDB + S3) per test file.
As discussed with @olizilla , each test creates its internal resources (tableName, bucketName) while keeping using same Docker containers:
- a simple `prepareResources` function is used to create the test specific resources
- could be done in `beforeEach`, but this might create issues running tests in parallel as same references would be used to track tableName, bucketName
- names of the resources are propagated to `ucantoServer` creation to be used within the code (previously, they were in general context)
- creating access mock server in `beforeEach` still. Main reason is tests keeping track of counting calls which would be problematic. Given it does not spin any container keeping for now
> chore: restructure tests to start container per test file

- api/package.json
- api/tables/index.js
- api/test/service/store.test.js
- api/test/service/upload.test.js
- package-lock.json
- stacks/api-stack.js
pull the table definitions into api/tables/index.js and reuse them in both infra and test code.
provides `dynamoDBTableConfig` fn to convert SST table definition to DynamoDB CreateTableCommandInput
License: MIT
> feat: share table schema between infra and test code

- api/service/store/add.js
- api/service/store/list.js
- api/service/store/remove.js
- api/service/types.ts
- api/service/upload/add.js
- api/service/upload/list.js
- api/service/upload/remove.js
- api/tables/index.js
- api/tables/store.js
- api/tables/upload.js
- api/test/service/store.test.js
- api/test/service/upload.test.js
Update the dynamoDB table schema to the following:
```js
/** @type TableProps */
export const storeTableProps = {
fields: {
space: 'string',        // `did:key:space`
link: 'string',         // `bagy...1`
size: 'number',         // `101`
origin: 'string',       // `bagy...0` (prev CAR CID. optional)
issuer: 'string',       // `did:key:agent` (issuer of ucan)
invocation: 'string',   // `baf...ucan` (CID of invcation UCAN)
insertedAt: 'string',   // `2022-12-24T...`
},
// space + link must be unique to satisfy index constraint
primaryIndex: { partitionKey: 'space', sortKey: 'link' },
}
/** @type TableProps */
export const uploadTableProps = {
fields: {
space: 'string',        // `did:key:space`
sk: 'string',           // `root#shard` + space must be unique for dynamo index constraint
root: …
```
> feat!: update table schema

- api/buckets/data-cid-to-car-cid-store.js
- api/buckets/dudewhere-store.js
- api/functions/ucan-invocation-router.js
- api/package.json
- api/service/types.ts
- api/service/upload/add.js
- api/test/helpers/ucanto.js
- api/test/service/upload.test.js
- package-lock.json
Write mapping (data CID -> car CID) into Dudewhere. It includes:
- bucket abstraction layer similar to what we have for carpark
- `upload/add` updated to write entries into Dudewhere by relying on bucket abstraction layer
- doing same retry approach as we do in CF hosted API
Questions:
- wondering if we should just use dudewhere naming instead of long `data-cid-to-car-cid-store`. We will lose readability, but maybe we want same pattern as calling `carpark` everywhere. Thoughts?
Closes #39
> feat: write mapping to dudewhere on upload add

- README.md
- api/functions/ucan-invocation-router.js
- stacks/replicator-stack.js
- stacks/satnav-stack.js
Adds env variables to the docs. Meanwhile discovered two issues with env variables:
- last replicator PR start using new pattern with `REPLICATOR_ENDPOINT` instead of `REPLICATOR_ACCOUNT_ID`. It is used already in lambda invoked https://github.com/web3-storage/upload-api/blob/main/replicator/functions/replicator.js#L15
- SATNAV_BUCKET_NAME was being injected in ENV Vars, but we don't need it anymore with latest refactors. We can just pass bucketName from reference.
TODO:
> fix: env variables

- api/functions/get.js
- api/functions/ucan-invocation-router.js
- api/package.json
- carpark/event-bus/eipfs-indexer.js
- carpark/functions/carpark-bucket-event.js
- carpark/package.json
- package-lock.json
- package.json
- replicator/functions/replicator.js
- replicator/package.json
- satnav/functions/satnav-bucket-event.js
- satnav/functions/satnav-writer.js
- satnav/package.json
- stacks/api-stack.js
- stacks/bus-stack.js
- stacks/carpark-stack.js
- stacks/config.js
- stacks/replicator-stack.js
- stacks/satnav-stack.js
Adds Sentry to project based on https://blog.sentry.io/2022/02/03/guest-post-how-to-monitor-lambda-functions-in-your-sst-application/
Needs:
Closes #20
> feat: add sentry

- stacks/carpark-stack.js
> I get an upload URL! ...but
> `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://carpark-staging-0.s3.us-east-2.amazonaws.com/`
Add CORS config to carpark bucket to allow uploads via signed URLs.
License: MIT
> fix: make carpark cors again

- api/service/index.js
This was missing from #59 and errors happening within ucanto service were not being propagated to sentry
> fix: add sentry exception to ucanto server catch

- docs/s3-presigned-url.md
I've been digging into presigned URLs for a couple of days, and wanted to capture what I know, so i can read it when i forget next week.
I've stuck to the facts here and added my conjecture in #78 
License: MIT
> docs: add notes on s3 presigned url generation

- upload-api/service/types.ts
- upload-api/service/upload/remove.js
- upload-api/tables/upload.js
- upload-api/test/service/upload.test.js
Allows a caller to optionally call store/remove with the shards to completely remove a thing.
Needed by https://github.com/web3-storage/w3cli/pull/20
License: MIT
> feat: return the removed item from upload/remove

- upload-api/config.js
- upload-api/functions/get.js
- upload-api/functions/ucan-invocation-router.js
- upload-api/service/index.js
- upload-api/test/config.test.js
- upload-api/test/helpers/ucanto.js
- upload-api/test/service/upload.test.js
Motivation:
* @alanshaw informed me via slack that upload-api signs invocations sent to access-api. These signatures wouldn't be verifiable if their signer did was a non-key-did.
What
* This PR makes it so the service signer for most of upload-api knows nothing about `env.UPLOAD_API_DID`.
* `env.UPLOAD_API_DID` only is used for the Principal passed to the ucanto server id (to verify incoming invocations 'aud')
* similar to this I did for w3protocol https://github.com/web3-storage/w3protocol/pull/303
* /version api response object has new property `aud`, which is the expected `aud` value of any UCAN invocations sent to the ucanto server (when env.UPLOAD_API_DID is set, it'll be that did)
> fix: upload-api doesn't use a did:web as the serviceSigner in accessClient

- stacks/carpark-stack.js
- stacks/config.js
- stacks/index.js
- stacks/satnav-stack.js
- stacks/ucan-invocation-stack.js
- stacks/upload-db-stack.js
set `app.setDefaultRemovalPolicy(RemovalPolicy.DESTROY)` where stage is not `prod` or `staging`
- stage names are defined in seed.run as `prod` and `staging` and `pr<###>` in the environment specific settings
- docs: https://docs.sst.dev/advanced/removal-policy#changing-the-removal-policy
Remove big old config object in favour of simpler functions
- bucket names will be identical for staging and prod.
- PR buckets will now have nice names too!
License: MIT
> fix: destroy buckets for PR builds

- stacks/index.js
the replicator stack should be deployed! We need it to replicate things like car indexes to R2.
License: MIT
> feat: deploy replicator stack

- ucan-invocation/functions/ucan-bucket-event.js
must match the export the stack expects here: https://github.com/web3-storage/w3infra/blob/5ed9b190d6442fbce3e8d6421d9e6501d22e7ace/stacks/ucan-invocation-stack.js#L39
License: MIT
> fix: fix ucanBucketConsumer export

- upload-api/service/store/add.js
- upload-api/test/service/store.test.js
S3 max put size is 5GB, so we enforce that in store/add to avoid giving folks a PUT url they can't use.
see: https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html
fixes #97
License: MIT
> feat: enforce max single put size

- upload-api/service/store/list.js
- upload-api/service/store/remove.js
- upload-api/service/types.ts
- upload-api/service/upload/add.js
- upload-api/service/upload/list.js
- upload-api/service/upload/remove.js
- upload-api/test/service/upload.test.js
We previously added verification for `store/add`. We talked about doing same for upload but we did not.
In the context of `store`, we did not add validation for `list` and `remove` given it needed prior validations of a space being registered for add operations. In `upload` we should do the same. Otherwise, there is a vector where we can have our upload table written with uncontrolled number of non existing rows.
Closes https://github.com/web3-storage/w3infra/issues/37
> fix: verify space registered on upload add

- replicator/index.js
- replicator/test/helpers/context.js
- replicator/test/index.test.js
We have `sha256` as an attribute in our bucket entries. This could enable us to use S3's `GetObjectAttributesCommand` to get the sha256 of this. However, we can't follow same pattern as `dotStorage workers` because CF Workers have an internal API for R2 that supports sha256, while S3 API is still [not](https://developers.cloudflare.com/r2/data-access/s3-api/api/) compatible.
Moved towards trying to integrate md5, with the assumption of ETag header having md5 https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html in it and that we can use S3 Client for R2 with   ✅ Content-MD5
We get md5 ETag in base16 (thanks docs for not mentioning this anywhere 😘) wrapped with quotation marks and S3 client for PutObjectCommand expects the base64-encoded 128-bit MD5 digest of the …
> feat: data integrity using md5

- .env.tpl
- .gitignore
- README.md
- package-lock.json
- package.json
- test/helpers/context.js
- test/helpers/deployment.js
- test/upload-api.test.js
This PR adds the basic setup for integration tests. It relies on https://seed.run/docs/adding-a-post-deploy-phase.html to run the integration tests once seed.run finishes its deploy. You can see output in: https://console.seed.run/dag-house/w3infra/activity/stages/pr122/builds/16/post-deploy In case post deploy [fails](https://console.seed.run/dag-house/w3infra/activity/stages/pr122/builds/15/post-deploy), it is marked as failing in github CI too 👍🏼 
After this approach is validated, we should in follow up PRs to the actual interesting integration tests. Such as, using w3up client to interact with upload API, and checking its dynamoDB, buckets, R2, etc to guarantee everything happened as expect.
By default, not running `integration tests` with normal unit tests script. Main reason for …
> test: integration tests setup

- package-lock.json
- package.json
- stacks/carpark-stack.js
- stacks/satnav-stack.js
- test/helpers/deployment.js
- test/upload-api.test.js
Adds integration tests for remaining sst stacks. It includes:
- Check carpark bucket got car file written into
- Check satnav stack did its thing and created side index file for uploaded CAR
- Check replicator did its thing, getting CAR replicated to CF carpark, as well as satnav side index
Needs:
Closes #9
> test: integration tests sst stacks

- README.md
- stacks/carpark-stack.js
This PR makes our carpark to rely on E-IPFS SQS for indexing based on a provided ENV variable. This way, we can setup dev/staging to use staging E-IPFS while prod to use prod one
[seed.run](https://console.seed.run/dag-house/w3infra/settings/stages/staging) environments were set with new Env var for all envs
> fix: eipfs indexer with environment variable arn

- README.md
adds missing `ucan-invocation` in repo structure description
> docs: ucan invocation stream in repo contents

- upload-api/service/types.ts
- upload-api/tables/store.js
- upload-api/tables/upload.js
- upload-api/test/service/store.test.js
- upload-api/test/service/upload.test.js
After chatting with @alanshaw I did a quick survey of naming conventions for bidirectional paging. After reviewing the following:
- https://theburningmonk.com/2018/02/guys-were-doing-pagination-wrong/ - before/after
- https://gist.github.com/tspecht/f4b53e34a2ccf1bdef2c8fb9a475ca05 - startCursor/endCursor
- https://medium.com/hackernoon/bi-directional-cursor-pagination-with-react-js-relay-and-graphql-dc4ad6f9cbb0 before/after
- https://www.apollographql.com/docs/react/pagination/cursor-based/#relay-style-cursor-pagination before/after
- relay's official paging spec uses before/after - https://relay.dev/graphql/connections.htm
I proposed renaming `startCursor` and `endCursor` to `before` and` after` and de-deprecating cursor.
This results in a paging API that should feel ergonomic to …
> feat!: rename startCursor and endCursor to before and after

- stacks/upload-api-stack.js
Temporary fix for CI issue from https://github.com/serverless-stack/sst/issues/2587 as suggested in https://github.com/serverless-stack/sst/issues/2587#issuecomment-1455875437
The fix simply tweaks the `accessLog` format to not include the `cognitoIdentityId` like fix from sst https://github.com/serverless-stack/sst/pull/2602/files
In the meantime, hopefully sst team provides a fix for v1, or we need to work on landing our update https://github.com/web3-storage/w3infra/pull/152 . I started by trying to update, but after spending over 2 hours debugging random CI SegFaults and other deployment issues decided to punt on this for now. v2 is quite recent and maybe we should stay in v1 some more time given these SegFault errors are likely not related to our code...
> fix: temporary fix for access log format to allow http gateway deploy

- stacks/ucan-invocation-stack.js
- ucan-invocation/constants.js
- ucan-invocation/functions/metrics-upload-remove-total.js
- ucan-invocation/tables/metrics.js
- ucan-invocation/test/functions/metrics-upload-remove-total.test.js
- ucan-invocation/types.ts
Part of metrics work https://github.com/web3-storage/w3infra/issues/117
Adds system total metrics for  `upload/remove`. With these, we can track number of uploads unlinked from space
Needs:
> feat: ucan stream consumer upload remove

- test/integration.test.js
- upload-api/functions/metrics.js
> fix: api prometheus bytes naming

- stacks/upload-api-stack.js
AWS API Gateway does not know trailing slash... and Grafana Agent puts trailing slash
See:
- https://repost.aws/questions/QUuoQUNhpDRxWufwWJKIU6Uw/can-you-invoke-api-gateway-with-just-a-hostname-and-without-a-trailing-slash
- https://forum.serverless.com/t/switching-to-http-api-and-trailing-slash-issue/12717
> fix: metrics http api handler accepting trailing slash

- test/integration.test.js
- ucan-invocation/constants.js
- upload-api/functions/metrics.js
Adds other system metrics to metrics endpoint
```
w3up_bytes{can="store/add"} 197
w3up_bytes{can="store/remove"} 0
w3up_invocations_total{can="store/add"} 1
w3up_invocations_total{can="store/remove"} 0
w3up_invocations_total{can="upload/add"} 0
w3up_invocations_total{can="upload/remove"} 1
```
See https://pr165.up.web3.storage/metrics ✨ 
Needs:
> feat: add new system metrics to metrics endpoint

- package-lock.json
- stacks/ucan-invocation-stack.js
- test/integration.test.js
- ucan-invocation/constants.js
- ucan-invocation/functions/space-metrics-store-add-total.js
- ucan-invocation/functions/space-metrics-store-remove-total.js
- ucan-invocation/package.json
- ucan-invocation/tables/space-metrics.js
- ucan-invocation/test/functions/metrics-store-add-size-total.test.js
- ucan-invocation/test/functions/metrics-store-add-total.test.js
- ucan-invocation/test/functions/metrics-store-remove-total.test.js
- ucan-invocation/test/functions/metrics-upload-remove-total.test.js
- ucan-invocation/test/functions/space-metrics-store-add-total.test.js
- ucan-invocation/test/functions/space-metrics-store-remove-total.test.js
- ucan-invocation/test/helpers/tables.js
- ucan-invocation/types.ts
Part of metrics work https://github.com/web3-storage/w3infra/issues/117
Adds space counters for `store/add` and `store/remove`.
> feat: ucan stream consumer space store add and remove count

- stacks/ucan-invocation-stack.js
- test/integration.test.js
- ucan-invocation/functions/metrics-upload-add-total.js
- ucan-invocation/tables/metrics.js
- ucan-invocation/test/functions/metrics-upload-add-total.test.js
- ucan-invocation/types.ts
Part of metrics work https://github.com/web3-storage/w3infra/issues/117
Adds system total metrics for  `upload/add`. With these, we can track number of uploads linked to a space. As we agreed, once we land receipts we can revisit this to be associated with receipt to track uniqueness
> feat: ucan stream consumer system upload add count

- stacks/ucan-invocation-stack.js
- test/integration.test.js
- ucan-invocation/functions/space-metrics-store-add-size-total.js
- ucan-invocation/functions/space-metrics-store-remove-size-total.js
- ucan-invocation/tables/space-metrics.js
- ucan-invocation/test/functions/space-metrics-store-add-size-total.test.js
- ucan-invocation/test/functions/space-metrics-store-remove-size-total.test.js
- ucan-invocation/test/helpers/context.js
- ucan-invocation/types.ts
Part of metrics work https://github.com/web3-storage/w3infra/issues/117
Adds space accumulated metric for `store/add` and `store/remove` size. With these, we can track total size of CARs requested for deletion. Until we have receipts, we will rely on the bucket to perform a Head request (given we do not have GC as well for now)
> feat: ucan stream consumer space size track

- stacks/ucan-invocation-stack.js
- ucan-invocation/constants.js
- ucan-invocation/functions/metrics-store-add-size-total.js
- ucan-invocation/functions/metrics-store-add-total.js
- ucan-invocation/functions/metrics-store-remove-size-total.js
- ucan-invocation/functions/metrics-store-remove-total.js
- ucan-invocation/functions/metrics-upload-add-total.js
- ucan-invocation/functions/metrics-upload-remove-total.js
- ucan-invocation/functions/space-metrics-store-add-size-total.js
- ucan-invocation/functions/space-metrics-store-add-total.js
- ucan-invocation/functions/space-metrics-store-remove-size-total.js
- ucan-invocation/functions/space-metrics-store-remove-total.js
- ucan-invocation/functions/space-metrics-upload-add-total.js
- ucan-invocation/functions/space-metrics-upload-remove-total.js
- ucan-invocation/test/functions/metrics-store-add-size-total.test.js
- ucan-invocation/test/functions/metrics-store-add-total.test.js
- ucan-invocation/test/functions/metrics-store-remove-size-total.test.js
- ucan-invocation/test/functions/metrics-store-remove-total.test.js
- ucan-invocation/test/functions/metrics-upload-add-total.test.js
- ucan-invocation/test/functions/metrics-upload-remove-total.test.js
- ucan-invocation/test/functions/space-metrics-store-add-size-total.test.js
- ucan-invocation/test/functions/space-metrics-store-add-total.test.js
- ucan-invocation/test/functions/space-metrics-store-remove-size-total.test.js
- ucan-invocation/test/functions/space-metrics-store-remove-total.test.js
- ucan-invocation/test/functions/space-metrics-upload-add-total.test.js
- ucan-invocation/test/functions/space-metrics-upload-remove-total.test.js
- ucan-invocation/types.ts
This PR hooks kinesis consumers with receipts, instead of previous world where it would hook up with workflows. For this, it simply filters out Kinesis events that are not receipts as they should not be account for the metrics we want to track at the moment.
As talked in today`s morning sync, setting up a new Kinesis stream so that:
- we reset clock history of 1 year
- we still keep old stream around so that we can persist what is there to S3 (or even re-process it and pipe to the new stream with receipts and needed files in correct buckets!)
> feat: ucan stream handles receipts

- ucan-invocation/functions/metrics-store-add-size-total.js
- ucan-invocation/functions/metrics-store-add-total.js
- ucan-invocation/functions/metrics-store-remove-size-total.js
- ucan-invocation/functions/metrics-store-remove-total.js
- ucan-invocation/functions/metrics-upload-add-total.js
- ucan-invocation/functions/metrics-upload-remove-total.js
- ucan-invocation/functions/space-metrics-store-add-size-total.js
- ucan-invocation/functions/space-metrics-store-add-total.js
- ucan-invocation/functions/space-metrics-store-remove-size-total.js
- ucan-invocation/functions/space-metrics-store-remove-total.js
- ucan-invocation/functions/space-metrics-upload-add-total.js
- ucan-invocation/functions/space-metrics-upload-remove-total.js
- ucan-invocation/test/functions/metrics-store-add-size-total.test.js
- ucan-invocation/test/functions/metrics-store-add-total.test.js
- ucan-invocation/test/functions/metrics-store-remove-size-total.test.js
- ucan-invocation/test/functions/metrics-store-remove-total.test.js
- ucan-invocation/test/functions/metrics-upload-add-total.test.js
- ucan-invocation/test/functions/metrics-upload-remove-total.test.js
- ucan-invocation/test/functions/space-metrics-store-add-size-total.test.js
- ucan-invocation/test/functions/space-metrics-store-add-total.test.js
- ucan-invocation/test/functions/space-metrics-store-remove-size-total.test.js
- ucan-invocation/test/functions/space-metrics-store-remove-total.test.js
- ucan-invocation/test/functions/space-metrics-upload-add-total.test.js
- ucan-invocation/test/functions/space-metrics-upload-remove-total.test.js
- ucan-invocation/types.ts
- ucan-invocation/utils/receipt.js
- upload-api/test/ucan-invocation.test.js
- upload-api/ucan-invocation.js
We need to know in UCAN Stream if receipt is from a success invocation or not. Therefore passing `out` from receipt in and validate in consumers
> fix: ucan stream checking receipt output

- upload-api/functions/ucan-invocation-router.js
Cleans up #196 and avoids redundant decode+encode when request is already desired format
> chore: avoid transcode unless necessary

- upload-api/buckets/delegations-store.js
- upload-api/errors.js
- upload-api/functions/ucan-invocation-router.js
- upload-api/functions/validate-email.js
- upload-api/tables/delegations.js
- upload-api/tables/index.js
- upload-api/tables/subscription.js
- upload-api/test/queries.test.js
- upload-api/test/service/delegations.test.js
- upload-api/types.ts
Since we already store delegations inside invocations in the invocation log, we can simply store the invocation CID and delegation CID and then fetch and find the needed delegations when they are requested.
I'm not sure the implementation is correct, as I'm not super familiar with the distinction between invocations, workflows and receipts, but the types all check out!
Would love careful review on the new `findDelegationInInvocation` method I've added to `upload-api/tables/delegations.js`
> feat: stop storing delegations in a bespoke bucket

- docs/roundabout.md
- roundabout/functions/redirect.js
- roundabout/index.js
- roundabout/test/index.test.js
- roundabout/utils.js
- stacks/roundabout-stack.js
- test/helpers/context.js
- test/helpers/deployment.js
- test/roundabout.test.js
There is also requirement to be able to create presigned URLs for [dagcargo bucket](https://dash.cloudflare.com/fffa4b4363a7e5250af8357087263b3a/r2/default/buckets/dagcargo). It does not have same format as carpark.
This PR adds a `GET /raw/{key}` endpoint to the API Gateway under roundabout. It enables to pass a raw key of a bucket, rather than a CID that is converted to the carpark key format. By default, it still picks `carpark` bucket if no bucket is provided.
Integration tests were added so that we can actually test the deployment, so that env vars and permissions are validated
Alternatively, we could consider not to be opinated about key key format and always receive a raw key. However, I think it makes sense to move into a way that we create key for carpark. There are a few …
> feat: roundabout supports redirect to raw key with bucket as query param

- upload-api/tables/index.js
We need to be able to figure out which space a CAR CID was added to.
Not adding anything more than the Dynamo index for now because:
a) we use the Dynamo console for blocking for now and b) we haven't designed the capabilities that will use this yet
this supercedes https://github.com/web3-storage/w3infra/pull/121/files
> feat: add CID index to store table

- package-lock.json
- upload-api/functions/ucan-invocation-router.js
- upload-api/package.json
- upload-api/tables/consumer.js
- upload-api/tables/space-metrics.js
upgrade w3up to bring in new tests that would have caught these bugs
> fix: fix a number of bugs with ProvisionStore#getConsumer

- package-lock.json
- upload-api/package.json
- upload-api/service.js
Adds limit based on previous decisions, considering that S3 Put command has hard-limit of 5GiB.
- By limiting CAR size to 127*(1<<25), we guarantee max-4GiB-padded Filecoin pieces and have better utilization of Fil sector space.
- By receiving one more byte, we would immediatly get to 8GiB padded piece.
Closes https://github.com/web3-storage/w3up/issues/827
> fix: limit max upload size

- .gitignore
- filecoin/errors.js
- filecoin/functions/piece-cid-compute.js
- filecoin/index.js
- filecoin/package.json
- filecoin/tables/index.js
- filecoin/tables/piece.js
- filecoin/test/compute-piece-cid.test.js
- filecoin/test/helpers/context.js
- filecoin/test/helpers/resources.js
- filecoin/test/helpers/tables.js
- filecoin/types.ts
- package-lock.json
- package.json
- stacks/filecoin-stack.js
- stacks/index.js
- stacks/upload-db-stack.js
- test/demo-test.js
- test/helpers/context.js
- test/helpers/table.js
- test/integration.test.js
- tsconfig.json
- upload-api/package.json
This is the first of a series of PRs to integrate w3up with w3filecoin.
This PR adds Filecoin Stack, where CARPARK bucket is hooked up with a lambda to compute Piece CIDs via Event Bus events. A queue is in the middle to keep the flow steady. Once a PR is computed, its details are written into a DynamoDB table. This will have all the information users might need to ask, in order to then ask Deal Tracker for information for a given deal. In other words, it maps `piece`, `link` (Car CID), `aggregate` and `inclusionProof` (TBD what it actually is, is it a CID for a stored file in a bucket?).
Also integration tests were added.
In a follow up PR, a event will be hooked up from DynamoDB table insert to trigger `segment/add` capability from Aggregator together with writing a claim to equivalency …
> feat: compute piece for uploaded cars

- stacks/config.js
- stacks/ucan-invocation-stack.js
We are currently being billed quite a bit in AWS for all the Kinesis streams we keep open for dev/CI.
This PR addresses this by:
- not deploying 2 kinesis streams per env to keep historical content. We really just need the production stream still deployed until we read it.
- we can also decrease the persistence of the streams to keep costs down
As follow ups, we should also consider (I will create issues):
- tool that proactively tears down running infrastructure for stalled PRs (or setup tests in a way that kinesis is put on and off for the tests)
- get historical content kinesis stream flushed out
> fix: reduce costs on kinesis streams

- package-lock.json
- package.json
- stacks/firehose-stack.js
merging into #191 - mostly put this up so @vasco-santos can review before I push it into the PR he opened!
- implement date based partitioning
- expand `value` and `out` struct definitions to allow for more interesting queries
> feat: kinesis delivery stream updates

- stacks/firehose-stack.js
Plus example query joining dynamo to ucan logs.
Additionally,  after chatting with @dchoi27 this morning, two major optimizations:
1. partition by `type` and rework the ucan table to only look at "receipts" - everything in "workflows" shows up in receipts so this reduces the amount of data scanned by ~50%
2. partition by `op` to allow us to create tables that only query a specific operation (ie, `store/add` or `provider/add`) - this lets us add operation-specific schemas with much less clutter in result types
Using these optimizations, I've added standalone tables for `store/add`, `upload/add` and `provider/add` UCANs. I will rework the saved queries to use them next.
> feat: add dynamo connector and rework tables

- stacks/firehose-stack.js
this will let us figure out the first time something is uploaded
also add more ops to the receipts table projection enum so that we can query for any capability type in the system as of today.
> feat: add status to athena store/add table

- stacks/firehose-stack.js
Add two more capability tables to Glue so Athena can query them.
I'd like to start doing this in an automated way at some point, but that doesn't feel high priority enough for the moment so I've filed an issue here:
https://github.com/web3-storage/w3infra/issues/243
> feat: add two more capability tables for Athena

- test/helpers/up-client.js
- test/integration.test.js
- upload-api/stores/provisions.js
this is just a matter of changing how we generate subscription IDs. they are now generated from customer AND consumer, which means they will be unique for a given customer/consumer pair - in other words, a given customer will only be able to provision a given space one time.
> feat: allow customers to create more than one space

- filecoin/functions/piece-cid-compute.js
- stacks/config.js
- stacks/filecoin-stack.js
So that we can transition into new deployments for w3filecoin without creating noise in w3infra with errors. 
This was test data and is also still with outdated PieceCIDv2
> feat: compute piece cid behind env var

- billing/functions/ucan-stream.js
- billing/lib/api.ts
- billing/test/lib/ucan-stream.js
- package-lock.json
Turns out `invocationCid` is only set on receipt messages.
> fix: ucan message types and parser

- billing/data/consumer.js
- billing/data/customer.js
- billing/data/subscription.js
- billing/lib/api.ts
- billing/tables/client.js
Some fields i.e. `cause` because required after a certain time so need to be marked optional in the types and expected to be `undefined` sometimes when encoding/decoding.
Other fields like `updatedAt` are explicitly only set when the record has been updated.
> fix: allow optional fields

- filecoin/index.js
Fixes the issue with the way digest had been computed. Since digest size depends on padding which depends on payload size we can not know what it will be until we're done feeding payload.
Issue is fixed by allocating buffer only after we're done writing into hasher.
> fix: piece digest function

- billing/data/space-diff.js
- billing/functions/ucan-stream.js
- billing/lib/api.ts
- billing/lib/space-billing-queue.js
- billing/lib/ucan-stream.js
- billing/tables/space-diff.js
- billing/tables/space-snapshot.js
- billing/tables/usage.js
- billing/test/helpers/context.js
- billing/test/lib/api.ts
- billing/test/lib/space-billing-queue.js
- billing/test/lib/ucan-stream.js
- docs/billing.tldr
- filecoin/test/filecoin-service.test.js
- stacks/billing-stack.js
There's no reason for space diffs to store the customer, or include it in the partition key 🤦. If the customer for a given space changes we cannot accurately account for space size changes. I'm not sure why it would, but if it did we'd not be able to get an accurate list of changes for a space.
Also, for retrieving usage in the frontend it's also problematic as we have to somehow look up the customer for a given space before we can get hold of the diffs.
> fix: change partition key for space diff to not use customer

- stacks/upload-db-stack.js
- test/filecoin.test.js
We will restart the Filecoin Pipeline for launch. So, let's create a `piece-v2` table
Given Dynamo makes it difficult to clean an entire table (and expensive!) it is better to just create a new Table to re-start the pipeline. We could also delete the table and re-deploy, however most of the content already there will still at some point be put into Filecoin deals, so already knowing their PieceCIDv2 will mean less compute costs.
> feat: new piece table for storefront

- filecoin/store/receipt.js
- stacks/ucan-invocation-stack.js
- stacks/upload-api-stack.js
- test/filecoin.test.js
- upload-api/buckets/invocation-store.js
- upload-api/functions/receipt.js
- upload-api/types.ts
Adds receipts endpoint with redirect to workflow bucket where receipt for asked task will be available.
Bucket was made public to accept GETs, you can see the generated policy [here](https://s3.console.aws.amazon.com/s3/buckets/workflow-store-pr275-0?region=us-east-2&tab=permissions) . IAM Role has general access to the bucket, while `"Principal": "*"` can perform `GetObject`.
Integration tests were added to inspect receipt from `filecoin/offer` invocation
> feat: add receipts endpoint

- stacks/firehose-stack.js
We renamed caps, but this did not get reflected here 🤦🏼‍♂️  
It keeps the alphabetical order previously in place
> fix: ucan firehose receipt table op values with new filecoin names

- stacks/firehose-stack.js
Adds query to calculate hours to data commited of aggregates over last 7 days by seeing difference between time of `aggregate/offer` and `aggregate/accept` receipts.
You can copy query
```sql
WITH
accepted_aggregates AS (
SELECT value.att[1].nb.aggregate._cid_slash as cid, ts as accept_ts FROM "AwsDataCatalog"."prod-w3infra-ucan-stream-delivery-database-0"."prod-w3infra-aggregate-accept-table-0" WHERE ts >= (CURRENT_TIMESTAMP - INTERVAL '7' DAY)
)
select cid, ts as offer_ts, accept_ts, CAST((to_unixtime(accept_ts) - to_unixtime(ts))/3600 as integer)  as hours_to_data_commited FROM "AwsDataCatalog"."prod-w3infra-ucan-stream-delivery-database-0"."prod-w3infra-aggregate-offer-table-0" INNER JOIN accepted_aggregates ON accepted_aggregates.cid = value.att[1].nb.aggregate._cid_slash;
``` 
and …
> feat: glue query for hours to data commited over last 7 days

- package-lock.json
- stacks/firehose-stack.js
- stacks/ucan-invocation-stack.js
- ucan-invocation/buckets/workflow-store.js
- ucan-invocation/constants.js
- ucan-invocation/errors.js
- ucan-invocation/filecoin.js
- ucan-invocation/functions/metrics-aggregate-accept-total.js
- ucan-invocation/functions/metrics-aggregate-offer-total.js
- ucan-invocation/functions/utils.js
- ucan-invocation/package.json
- ucan-invocation/stores/filecoin-metrics.js
- ucan-invocation/tables/metrics.js
- ucan-invocation/test/functions/metrics-aggregate-accept-total.test.js
- ucan-invocation/test/functions/metrics-aggregate-offer-total.test.js
- ucan-invocation/test/helpers/ucanto.js
- ucan-invocation/types.ts
- upload-api/functions/metrics.js
Adds filecoin metrics for ucan stream in the same pattern we track other metrics in https://up.web3.storage/metrics
We want to rely on UCAN Stream metrics table to in a "prometheus style" increment metrics over time for totals.  There are some metrics in Firehose that we can rely on for ad-hoc queries and business queries (like monthly usage). More than the price and efficiency in the long run for totals in the Firehose, there are some limitations that are explicit here:
- we use PieceCids to encode Piece size, which we will never be able to handle in Athena level as we cannot decode the CID to get the size
- UCAN invocations (like aggregate/offer) may rely on attached blocks to move attachments with the invocation, while only identifying the CID for them. E.g in `aggregate/offer` we …
> feat: filecoin metrics for ucan stream prometheus and updates metrics endpoint

- billing/data/space-diff.js
🙈 🙈 🙈 
We currently have sort keys like:
```
Wed Nov 15 2023 16:23:16 GMT+0000 (Coordinated Universal Time)#bafyreiaaqkc6e2rcij7tipadffmqrdfcwbztcms3g7ayktyterfascn3xm
```
...which does not sort as expected
> fix: sort key for space diffs

- stacks/filecoin-stack.js
We were counting aggregate offers before shipping w3up that in the end we reset state given the incident of upload spike of repeated data in multiple orders. We should not account for these in metrics see https://github.com/web3-storage/w3infra/pull/310
> fix: disable filecoin metrics to restart counter from w3up ship day

- stacks/filecoin-stack.js
- upload-api/functions/metrics.js
> We were counting aggregate offers before shipping w3up that in the end we reset state given the incident of upload spike of repeated data in multiple orders. 
See https://github.com/web3-storage/w3infra/pull/310 and https://github.com/web3-storage/w3infra/pull/311
> fix: restart filecoin metrics from w3up ship day

- stacks/upload-api-stack.js
It happened 5 days ago this deploy, so the failures that happened will still luckily be processed 
also: we check the metrics in the integration tests, I have no idea on how in staging it was working fine :exploding_head:
> fix: add bucket permissions to lambda

- roundabout/functions/redirect.js
- roundabout/piece.js
- test/filecoin.test.js
We are not serving some non CAR content from roundabout, which is blocking SPs from downloading all the pieces. This fixes that, if we have the bytes let's just send them. If they will not be there, we will still fail with 404
Skipping integration tests for filecoin. I will solve them in follow up PR
> fix: roundabout to serve any content cid stored

- roundabout/functions/redirect.js
- roundabout/piece.js
- roundabout/test/piece.test.js
We should keep also equivalent CIDs that are not CARs to attempt in the bucket to get presigned URL
We will try for each of them to check if it is in bucket and generate presigned URL per:
- https://github.com/web3-storage/w3infra/blob/fix/find-equivalent-cids-also-if-not-car-cid/roundabout/functions/redirect.js#L81C23-L81C36
- https://github.com/web3-storage/w3infra/blob/fix/find-equivalent-cids-also-if-not-car-cid/roundabout/index.js#L25
> fix: find equivalent cids also if not car cid

- test/filecoin.test.js
Did https://github.com/web3-storage/w3filecoin-infra/pull/89 to make aggregates more fast to get as they are smaller. Because of the extra new piece, I suspect some pieces were left behind
> fix: re-enable integration tests filecoin

- roundabout/index.js
- roundabout/test/index.test.js
@ribasushi did some profiling and roundabout is taking ~800ms just to return the 302 status code (when requesting bytes by PieceCID). Probably most of this time comes from waiting on the content claims response, but also looking into what else Roundabout handler does, it may be a good idea to just redirect to the presigned url without validating content is in the bucket. We save one request to the bucket, and given we only use roundabout in internal cases it should never be 404. But actually if it is 404, might make more sense to then have presigned url response to be 404 than server to throw an error.
Thoughts?
> fix: roundabout should just redirect to 404 presigned url when no car in bucket instead of redundant check

- docs/billing.md
Documentation for billing was missing.
Includes rendered image of billing infra:
> docs: add short doc on billing operations

- billing/scripts/dry-run.js
- billing/scripts/helpers.js
- stacks/filecoin-stack.js
This adds space size (in bytes) to the dry run report.
Also adds the new `did:web:free.web3.storage` plan (that NFT.Storage is using) to the pricing calculator.
> feat: add snapshot size to dry run report

- billing/lib/ucan-stream.js
- billing/package.json
- billing/test/helpers/did.js
- billing/test/lib/ucan-stream.js
- package-lock.json
* Use the blob allocate receipt to track space size additions.
* Use blob remove receipt to track space size reductions.
> feat(billing): support blob capabilities

- roundabout/constants.js
- roundabout/functions/redirect.js
- roundabout/index.js
- roundabout/piece.js
- roundabout/test/index.test.js
- roundabout/test/piece.test.js
- roundabout/utils.js
Part of https://github.com/w3s-project/project-tracking/issues/49
Note that currently Roundabout is used in production traffic for SPs to download Piece bytes, and is planned to be used by w3filecoin storefront to validate a Piece CID.
1. SPs request comes with a PieceCID, where we get equivalency claim for this Piece to some content.
2. In current world (`store/*` protocol), it will in most cases be a CAR CID that we can get from R2 `carpark-prod-0` as `carCid/carCid.car`. However, `store/add` does not really require this to be a CAR, so it could end up being other CIDs that are still stored with same key format in R2 bucket.
3. With new world (`blob/*` protocol), it will be a RAW CID that we can get from R2 `carpark-prod-0` as `b58btc(multihash)/b58btc(multihash).blob`. 
1. …
> feat: roundabout gets raw cids as blobs

- roundabout/globals.js
- roundabout/piece.js
> chore: remove nodejs 16 shims

- stacks/upload-api-stack.js
- upload-api/constants.js
- upload-api/functions/admin-metrics.js
- upload-api/functions/space-metrics.js
- upload-api/metrics.js
- upload-api/test/admin-metrics.test.js
- upload-api/test/helpers/context.js
- upload-api/test/helpers/random.js
- upload-api/test/space-metrics.test.js
- upload-api/types.ts
Adds blob metrics for admin and space to track:
- count `blob/add`
- sum `blob/add` (`nb.blob.size`)
- count `blob/remove`
- sum `blob/remove` allocated size
> fix: add blob metrics

- stacks/upload-api-stack.js
- upload-api/functions/ucan-invocation-router.js
Yesterday I was puzzled on why my local deployment of Integration tests was working, while CI was not with some random errors just in few tests (with similar error as previous lack of permissions). It turns out, it was more lack of permissions, together with some bad configuration.
This extra permissions and configuration are actually a consequence of a different deployment approach per environment on w3up infra compared to old E-IPFS infra. Let's see the details:
w3up infra deployments:
- `prod` => `us-west-2`
- `dev` such as `vasco` => `us-west-2`
- `staging` => `us-east-2`
- `pr` such as `pr369` => `us-east-2`
E-IPFS infra deployments:
- `prod` => `us-west-2`
- `staging` => `us-west-2`
Considering the above, when we would be in prod or dev, both infras would be deployed in same zone. …
> fix: ipni service configuration for non west 2 deployments

- upload-api/external-services/ipni-service.js
- upload-api/functions/ucan-invocation-router.js
- upload-api/test/helpers/ipni-service.js
- upload-api/test/helpers/ucan.js
When IPNI service writes to dynamo, use the `BlobsStorage` to get the actual download URL for a given multihash.
> fix: claim correct location

- package-lock.json
- package.json
- test/bridge.test.js
- test/filecoin.test.js
- test/helpers/deployment.js
- test/integration.test.js
Tests blob client with https://github.com/w3s-project/w3up/pull/1459
> fix: upgrade w3up client rc with receipt poll for accept

- stacks/firehose-stack.js
Adds blob capabilities to UCAN Firehose, and adds glue tables for the main capabilities.
See stream log store for formats: https://us-east-2.console.aws.amazon.com/s3/buckets/stream-log-store-pr375-0?region=us-east-2&bucketType=general&tab=objects
See glue tables:
- https://us-east-2.console.aws.amazon.com/glue/home?region=us-east-2#/v2/data-catalog/tables/view/pr375-w3infra-space-blob-add-table-0?database=pr375-w3infra-ucan-stream-delivery-database-0&catalogId=505595374361&versionId=latest
- https://us-east-2.console.aws.amazon.com/glue/home?region=us-east-2#/v2/data-catalog/tables/view/pr375-w3infra-blob-allocate-table-0?database=pr375-w3infra-ucan-stream-delivery-database-0&catalogId=505595374361&versionId=latest
- https://us-east-2.console.aws.amazon.com/glue/home?region=us-east-2#/v2/ …
> feat: add blob capabilities to ucan firehose

- package-lock.json
- package.json
- upload-api/external-services/ipni-service.js
- upload-api/package.json
This PR should help debugging issues uploading DAGs with MANY blocks.
Firstly it pulls in `upload-api@18.0.1` which has a [fix for returning the wrong response when we fail to extract and decode a sharded DAG index](https://github.com/storacha-network/w3up/commit/67ef2b02ab2d745e4a2f023cf03f58c2a6ee1e2f).
Secondly, it tweaks errors returned by the IPNI service to just include details of the error in the response, while logging to stderr on the server. I believe the error dynamo/SQS has a `bigint` somewhere in it, which cannot be serialized by Ucanto when retruning the response:
```
TypeError: Do not know how to serialize a BigInt
at AgentMessageStore.write (/upload-api/stores/agent.js:57:16)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at handle …
```
> fix: error messages

- billing/functions/ucan-stream.js
- test/blob.test.js
- test/bridge.test.js
- test/filecoin.test.js
- test/helpers/store.js
- test/helpers/up-client.js
- test/integration.test.js
- test/store.test.js
Better debug https://github.com/storacha-network/project-tracking/issues/75
This PR does 2 things:
1. Add logging to the ucanstream handler for Billing API, to see if it is properly parsing and saving space diffs when a user uploads
2. Adds checks of before and after on usage from the billing system to the `blob` and `store` integration tests -- this is based almost exactly on the way the UsageBar component fetches data in the console.
> Add logging to space state changes, tests of billing usage

- upload-api/stores/agent/stream.js
I believe this to be the root cause of https://github.com/storacha-network/project-tracking/issues/75
What I can see is that our invocations are freequently throwing exceptions on the API:
```
2024-06-22T02:16:16.257Z	b1e35d62-a193-4192-8b2f-e30484c63378	WARN	WriteError: Write to store has failed: TypeError: Do not know how to serialize a BigInt
at AgentMessageStore.write (/upload-api/stores/agent.js:57:16)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at handle (/node_modules/@web3-storage/upload-api/src/lib.js:111:23)
at ucanInvocationRouter (/upload-api/functions/ucan-invocation-router.js:298:20)
at processResult (/node_modules/src/awslambda.ts:326:50) {
cause: TypeError: Do not know how to serialize a BigInt
at JSON.stringify (<anonymous>)
at assert …
```
> fix: type error on JSON.stringify in Agent Store

- stacks/billing-stack.js
Help the billing iterator catch up
I think this should allow us to parallelize execution on the iterator without changing the code nor affecting other consumers.
Up the parallelization factor on the billing ucan stream handler to 10 -- see https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-parallelization-factor-for-kinesis-and-dynamodb-event-sources/ -- this will allow parallelization on the same shard, but without increasing batch size (which would require logic change)
> fix(billing): increase parallelization factor

- billing/queues/client.js
- billing/queues/lib.js
- billing/tables/client.js
- billing/tables/lib.js
As per recommendations in [Best Practices with Lambda](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.Lambda.BestPracticesWithDynamoDB.html) this PR ports a small chunk of code from content claims that caches DynamoDB and SQS clients after they are created. This allows existing connections to be reused for non-cold start invocations and should lower lambda running time.
> feat(billing): reuse DynamoDB and SQS clients

- stacks/filecoin-stack.js
The filecoin metrics consumer has been observed to take up to 10 seconds to execute and appears to be the reason that iterator age is continuously increasing.
This PR increases the parallelization factor so that multiple executions can consume the stream in parallel. It also increases the timeout for the lambda in line with other timeouts in the same stack. This is because errors occur when it takes 10 seconds, and it does not ever take longer - hinting that it sometimes needs longer.
Note: I believe it is fine to do this in parallel because the lambda simply issues increment (ADD) instructions to dynamo for the metrics, not SET.
> fix(filecoin): increase metrics consumer parallelization factor

- stacks/billing-stack.js
The UCAN stream handler for the billing stack cannot keep up with the number of items it needs to consume - iterator age is constantly increasing.
However it only needs to consider receipts (we already drop [non-reciept types here](https://github.com/storacha-network/w3infra/blob/d4166646772a2e51755f8a9a6345d52ae981c22f/billing/lib/ucan-stream.js#L16)).
This PR uses "filters" to reduce the number of invocations the handler receives, which should hopefully give it more time to process receipts it cares about.
More info: https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventfiltering.html#filtering-kinesis
> feat(billing): filter by type receipt

- stacks/upload-api-stack.js
The admin/space metrics deal only with receipts and discard anything that is not a receipt.
This should (hopefully) reduce iterator age and lambda invocations bill.
e.g. current admin metrics iterator age:
> feat: add filters for metrics consumers

- billing/functions/ucan-stream.js
- billing/package.json
- package-lock.json
- test/filecoin.test.js
This adds an LRU cache to the UCAN stream consumer for billing to allow us to process data for spaces with frequent writes a lot quicker (will also reduce our dynamo reads bill a little).
Previously we filtered lambda invocations items to only process receipts (instead of also invocations, which we simply dropped). This was working for 3 days but now iterator age has started increasing again.
The lambda simply reads from the consumer table and writes to the space diff table. The data from the consumer table almost never changes (it actually cannot right now - we haven't built this feature yet) so an in-memory cache should speed up execution for spaces with high write frequency. We're currently seeing runtimes of ~250ms (when we actually need to do some work - i.e. a lot of lambda …
> feat(billing): add consumer list cache to UCAN stream consumer

- billing/functions/ucan-stream.js
- billing/lib/api.ts
- billing/lib/ucan-stream.js
- billing/tables/client.js
- billing/tables/lib.js
- billing/tables/space-diff.js
- billing/test/lib/space-billing-queue.js
- billing/test/lib/ucan-stream.js
- stacks/billing-stack.js
This enables the UCAN stream handler to accept messages in batches, which should hopefully speed up processing of the stream and stop the backlog from growing.
It's ok for the whole batch to be retried on failure since the primary key does not change over time, so any records that succeeded to be written in a failed batch will just be overwritten on retry.
> feat: use batching for billing UCAN stream handler

- filecoin/package.json
- filecoin/store/piece.js
- package-lock.json
- tools/get-oldest-pieces-pending-deals.js
Updates the piece store to use paginated queries as required in v7.2.0 of `filecoin-api`.
> feat: integrate latest filecoin-api dependency

- stacks/firehose-stack.js
it looks like we set this bucket up to expire items - in retrospect I think we should have created a separate bucket for the UCAN log because this stream log store bucket was probably originally meant to store streaming items temporarily
disable expiration for now, but uncomment with a note
> fix: disable UCAN log expiration

- test/filecoin.test.js
currently, seed.run PRs fail 90%+ of the time because of the Filecoin test.
until we have a more reliable way to test the filecoin flow, the PR disables it.
the inserted comment suggests a few solutions -- either spinning up custom infra for w3filecoin pipeline on each pr to get more reliable results, or mocking out the pipeline
either way, this is the temporary fix -- I don't want to put in extra retries or anything -- we just need to find a better way to test, or investigate if there are in fact underlying issues, but in the meantime, other PRs need to get merged.
> Disable flaky filecoin test for now

- stacks/upload-api-stack.js
resolve https://console.seed.run/dag-house/w3infra/activity/stages/staging/builds/386/services/upload-api
Essentially cause the up.web3.storage domain apiID changes, it tries to recreate the domain record, and it can't. So the solution is don't change the API ID for the web3.storage domain. 
In order to match the existing deployment, this PR will not add the domain to the first API ID for the first hosted zone.
> fix(upload-api-stack): don't add domain to apiID on first zone

- upload-api/html-storacha/index.jsx
My storacha branded email validation page is rendering body text white and unreadable, cause it's just the browser default. Fix this
set text color for body text on storacha branded email validation page to black, rather than relying on browser default color
> fix(upload-api): make text color explicit

- stacks/config.js
use access service url from custom domain, even in prod
Now that we have two domains for prod, we need to use the custom domain rather than just forcing `up.web3.storage`
This issue only applies to prod which is why it didn't come up in previous testing.
> fix(config): don't force access service url

- filecoin/store/invocation.js
- filecoin/store/workflow.js
- filecoin/test/helpers/context.js
- package-lock.json
- package.json
- psa/config.js
- psa/functions/download.js
- psa/functions/hash.js
- psa/lib.js
- psa/package.json
- psa/test/helpers/bytes.js
- psa/test/helpers/dag.js
- psa/test/helpers/math.js
- psa/test/helpers/resources.js
- psa/test/lib.spec.js
- psa/util.js
- sst.config.ts
- stacks/config.js
- stacks/psa-stack.js
- stacks/upload-api-stack.js
- tsconfig.json
- upload-api/buckets/car-store.js
- upload-api/package.json
- upload-api/stores/blobs.js
Adds a temporary stack for the old Pinning Service API (PSA) data.
The stack creates 2 functions:
- `hash` given a root CID, find a CAR file in one of the configured buckets and calculate it's hash.
- `download` given a root CID, find a CAR file in one of the configured buckets and return a signed URL allowing temporary access to the data.
This is for the PSA migration tool in console.
1. Users list pinned root CIDs.
2. Users get hash of CAR file containing pinned data by calling `hash`.
3. Users `blob/add` CAR file.
4. (Maybe) users need to upload the CAR, so they call `download` to get a signed URL and then download the data, and upload it to Storacha.
> feat: add PSA stack

- upload-api/html-w3s/index.jsx
Looks like this was removed here https://github.com/storacha/w3infra/pull/417/files#diff-fe7ebd5c64b7ab6a78e2a72d2c708860905cc2b4591b564ebe7e5d1b4a7d5d4cL5 - not sure why linting didn't pick this up.
Fixes:
```
ReferenceError: preact is not defined
File "/var/task/upload-api/functions/validate-email.mjs", line 111928, col 7, in Object.ValidateEmail
preact.createElement("stripe-pricing-table", {
File "/var/task/upload-api/functions/validate-email.mjs", line 111380, col 52, in j
U2.__d = false, b15 && b15(t15), P5 = Z2.call(U2, F7, M4);
File "/var/task/upload-api/functions/validate-email.mjs", line 111313, col 15, in S
var s16 = j15(n16, o16 || E6, false, void 0, c16, false, i17);
File "/var/task/upload-api/functions/validate-email.mjs", line 111865, col 39, in new HtmlResponse
const …
```
> fix: re-add preact import

- billing/data/consumer.js
- billing/lib/api.ts
- billing/lib/ucan-stream.js
- billing/test/helpers/consumer.js
- billing/test/helpers/egress.js
- billing/test/lib/egress-traffic.js
- billing/utils/stripe.js
- upload-api/tables/consumer.js
- upload-api/tables/index.js
**Context**
While testing the Egress Tracking System in Staging, an error occurred indicating that the router couldn't resolve the customer:
```
✘ [ERROR] Failed to record egress for space did:key:z6MkkYoZNccuPxDxc8kh6YgPSZwyXCqeS2QYqhtQtYyEKYTt {
name: 'FieldError',
message: 'Object contains invalid field "customer":\n' +
'  - Expected value of type string instead got undefined'
...
```
**Issue**
The error arises because the `consumerTable.get` query does not include the `customer` field in its projection, despite the customer existing in `consumerTable` and being manually retrievable.
**Fix**
This PR updates the `consumerTable.get` query to ensure the `customer` field is projected correctly, allowing the router to resolve the customer as expected. It also fixes the related tests to …
> fix: consumerTable.get returns customer

- billing/tables/consumer.js
- upload-api/tables/consumer.js
- upload-api/tables/index.js
By creating a new Global Secondary Index (GSI) with a different name, we avoid any downtime for existing queries that rely on the current consumer index, and we don’t need to worry about temporarily losing data in that index.
This PR introduces the `consumerV2` index to the `consumerTable` and includes the `customer` attribute in the projection. It also updates the `consumerTable.get` query to use the new index.
> fix(consumerTable): new consumer index

- package-lock.json
- stacks/upload-api-stack.js
- upload-api/functions/sample.js
- upload-api/monitor.js
- upload-api/package.json
- upload-api/test/helpers/random.js
- upload-api/test/monitor.test.js
Adds a new endpoint `/sample` which outputs a `dag-json` encoded array of root CIDs registered by users, filtered by codecs the gateway renders natively (`dag-pb` and `raw`).
The endpoint accepts a `?size=` querystring to allow up to 10 CIDs to be retrieved.
This can be used for retrieval testing.
> feat: add upload root CID sampler

- README.md
type in the secrets command and wrong example value for STRIPE_ENDPOINT_SECRET
> fix: fix stripe testing documentation

- upload-api/functions/ucan-invocation-router.js
- upload-api/functions/ucan.js
I'd like to track down the UCAN pipeline WriteError issue we've been seeing in production, so enable 100% tracing for both of the related Lambdas in hopes that this will give me maximal information about the code the error is in.
> feat: trace all UCAN invocation traffic

- stacks/upload-api-stack.js
- test/blob.test.js
Configures the UCAN service to send `Access-Control-Max-Age` header allowing the `OPTIONS` response to be cached for 1 day.
Also be explicit about other CORS headers we send.
> feat: add CORS Access-Control-Max-Age header

- billing/functions/usage-table.js
- billing/lib/space-billing-queue.js
For some reason some space snapshots have been missed in the past, despite seemingly being in the DB and showing up in dry run.
Also throw if the usage table queue gets an empty message - if this is happening I'd like to understand why, and I'm suspicious that some of our usage tracking issues are messages that are somehow being created with no records.
> fix: add a bit more logging to help track down usage billing bugs

- billing/lib/ucan-stream.js
- billing/test/lib/ucan-stream.js
- upload-api/stores/agent/stream.js
This PR addresses the issue https://github.com/storacha/project-tracking/issues/199, where duplicate space diff entries were being created when uploading a file using `space/blob/add`.
**Context:** When the UCAN invocation router receives a request, it executes the invocation and writes the receipts to the stream, which is then processed by `billing/ucan-stream.js` to populate the diff table.
Unlike `store/add`, `space/blob/add` spawns three additional invocations: `web3.store/blob/allocate`, `http/put`, and `web3.store/blob/accept` before finalizing.  
Due to the way receipts are extracted from agent messages—which are a collection of invocations and receipts without a clear hierarchy—this structure causes the receipt from `web3.store/blob/allocate` to be sent to the stream twice:  
1. …
> fix: multiple space diffs

- billing/functions/usage-table.js
- stacks/billing-stack.js
1) use a CID as an idempotency key - some Stripe usage billing reporting requests were failing because the space DID was much longer than we expected and the idempotency key cannot be more than 255 characters - we were sending ~450 characters in many cases
2) properly configure the "on failure" queue for the usage table handler - the previous config didn't work, and no "on failure" destination was set for this, which is, I suspect, why we can't find any trace of some usage table insert hook invocations
> fix: two important usage billing fixes

- sst.config.ts
I did not realise we weren't already using `arm_64`. Turns out this change had been applied to `w3filecoin-infra` and `content-claims` but not here (aside from the PSA stack).
Switching to `arm_64` should reduce lambda costs.
> fix: switch to arm_64 architecture

- .env.tpl
- package.json
- pnpm-lock.yaml
- stacks/upload-api-stack.js
- stacks/upload-db-stack.js
- upload-api/functions/oauth-humanode-callback.js
- upload-api/stores/humanodes.js
- upload-api/tables/index.js
- upload-api/types.ts
Add a Humanode OAuth callback that will give a "free storage with no credit card" plan to a user who uses Humanode to prove they are a unique person.
The one remaining concern I have with this code is the duplication in the templates - we now have 4 blobs of HTML like this across the two OAuth handlers and I'm not sure the best way to consolidate - any thoughts @alanshaw ?
> feat: add Humanode verification callback

- upload-api/functions/ucan-invocation-router.js
We recently added the ability to pass custom headers to identify which Storacha client uses the Upload API (see: https://github.com/storacha/upload-service/pull/215). Now we need to capture the custom header for analytics.
- Updated the `ucan-invocation-handler` to log additional information if the `X-Client` custom header is present. 
- The logs are structured in JSON format that's easy to query in CloudWatch Logs.
- The `clientId` field will contain the actual value of the `X-Client` header which indicates the name and version of the Storacha Client + service/project it is integrated to, e.g: `Storacha/X (js; MCP/Y)` - where `X` =  major version of the Storacha Client, and `Y` =  major version of the service/project integration.
- The `requestId` allows us to correlate this specific log …
> feat: capture x-client header for analytics

- README.md
- stacks/upload-api-stack.js
- upload-api/functions/get.js
Serve a DID document like the following at `/.well-known/did.json`. It allows external entities to resolve and verify our `did:web`:
```json
{
"@context": "https://w3id.org/did/v1",
"id": "did:web:up.storacha.network",
"verificationMethod": [
{
"id": "did:web:up.storacha.network#owner",
"type": "Ed25519VerificationKey2020",
"controller": "did:web:up.storacha.network",
"publicKeyMultibase": "z6MknTPdpBGfFysJWCJn7SbhrAA7Xmp6ZCnjH9dPxJy2T7sk"
}
],
"assertionMethod": [
"did:web:up.storacha.network#owner"
],
"authentication": [
"did:web:up.storacha.network#owner"
]
}
```
> feat: add `GET /.well-known/did.json` route

- stacks/upload-api-stack.js
- upload-api/functions/oauth-callback.js
- upload-api/functions/oauth-humanode-callback.js
> Lambda was unable to configure your environment variables because the environment variables you have provided exceeded the 4KB limit. 
This PR changes the routes configuration for the upload-api stack so that each lambda is configured with the environment and permissions it needs. This is better from a security standpoint but also will help the `POST /` route (UCAN invocation router) stay below the 4KB limit for environment variables.
i.e. it removes stripe, github, humanode and referrals config from the UCAN invocation router config.
> fix: specify environment and permissions per route

- .env.tpl
- package-lock.json
- package.json
- stacks/upload-api-stack.js
- stacks/upload-db-stack.js
- upload-api/functions/oauth-humanode-callback.js
- upload-api/stores/humanodes.js
- upload-api/tables/index.js
- upload-api/types.ts
feat: add Humanode verification callback (#466) :
Add a Humanode OAuth callback that will give a "free storage with no credit card" plan to a user who uses Humanode to prove they are a unique person.
The one remaining concern I have with this code is the duplication in the templates - we now have 4 blobs of HTML like this across the two OAuth handlers and I'm not sure the best way to consolidate - any thoughts @alanshaw ?
> feat: port #466 to legacy prod hotfix

- pnpm-lock.yaml
- pnpm-workspace.yaml
- roundabout/constants.js
- roundabout/functions/redirect.js
- roundabout/index.js
- roundabout/package.json
- roundabout/piece.js
- roundabout/test/index.test.js
- roundabout/test/piece.test.js
This PR allows roundabout to redirect to storage nodes.
If the blob location is found in carpark bucket then create a signed URL as usual, otherwise redirect to URL in location claim.
Note: in order to redirect to nodes in other networks we this to land: https://github.com/storacha/js-indexing-service-client/pull/19
> fix: allow roundabout redirect to storage node

- upload-api/stores/blob-registry.js
When de-registering a blob the diff size should be a negative number.
> fix: blob deregister diff

- filecoin/functions/handle-piece-insert-to-content-claim.js
- stacks/filecoin-stack.js
This is causing OOM in the indexer.
Error
> contentclaims/ucanservice.go:31    publishing equals claim: %!w(*fmt.wrapError=&{publishing equals claim: caching provider results: comitting batch: OOM command not allowed when used memory > 'maxmemory'. 0x400055be60})
> fix: publish equals claims to legacy content claims service

- stacks/upload-db-stack.js
- upload-api/tables/index.js
This PR adds the new tables present in the new deploy to the legacy deploy. They are unused here but should hopefully allow deploy without conflict.
> fix: re-add tables from new deploy

- upload-api/functions/validate-email.jsx
the post-email plan picker is really an affordance for the CLI, but we can't update old versions of the CLI to pass along an `appName` fact so we have to go the other way - if `appName` is set to `tg-miniapp` or `console`, don't show the plan picker - users will see this UI when they go back to the app.
> fix: don't show pricing table after email confirmation to TG mini app or console users

- billing/scripts/dry-run/README.md
- billing/scripts/dry-run/dry-run.js
- billing/scripts/space-allocations-snapshot/index.js
- billing/scripts/utils.js
Adds three optional parameters to the dry run script: `from`, `to`, and `customer`.
These options are going to help @heyjay44 run the script for different time periods and specific customers as needed.
> refactor(billing): update dry run script to accept parameters

- upload-api/stores/blob-registry.js
This should mitigate `IndexNotFound` error when invoking `space/index/add`.
> fix: enable consistent reads in blob registry find function
