README.md, package-lock.json, package.json, sst.json, stacks/index.js
=> chore: rename to upload api

api/package.json, package-lock.json, package.json
This PR rearranges package.json files to have api package deps in its own package.json, rather than main one
=> fix: package json dependencies in api

api/functions/ucan-invocation-router.js
https://sentry.io/organizations/protocol-labs-it/issues/3795848827/?project=4504253926539264&query=is%3Aunresolved&referrer=issue-stream
Also made staging and production to actually have ENV vars for this!
=> fix: make r2 region to be auto

package-lock.json, package.json
Per https://github.com/web3-storage/w3infra/pull/85#discussion_r1045600886
=> chore: tweak clean script

README.md
Just fixing some bugs
License: MIT
=> docs: fix header and overview

stacks/upload-api-stack.js
https://sentry.io/organizations/protocol-labs-it/issues/3805158482/?query=is%3Aunresolved&referrer=issue-stream
=> fix: ucan bucket permissions in handler

package-lock.json, upload-api/config.js, upload-api/functions/get.js, upload-api/functions/ucan-invocation-router.js, upload-api/package.json, upload-api/service/index.js, upload-api/test/config.test.js
Uses ucanto's new embedded key resolution to wrap a signer in a key with a different method.
=> feat: embedded key resolution

upload-api/functions/get.js
Minor as the old repo url would redirect here, _but we must keep up with the times._
License: MIT
=> fix: correct repo url

pnpm-lock.yaml, upload-api/config.js, upload-api/functions/get.js, upload-api/package.json
* also add to homeGet
Motivation:
* https://github.com/web3-storage/w3infra/issues/105
=> feat(upload-api): versionGet endpoint has publicKey prop which is always a did:key

README.md
Should be https://github.com/web3-storage/w3protocol/tree/main/packages/upload-client#create-an-agent
=> docs: update example deps

.env.tpl, README.md, carpark/event-bus/eipfs-indexer.js, stacks/carpark-stack.js
SQS Client for E-IPFS needs to have env per environment too
Closes #130
=> fix: eipfs indexer with environment variable url

README.md
You dont need to configure an aws account locally, you can submit a PR and seed.run will deploy it.
Prompted by @travis' experience of getting started with this repo!
=> docs: clarify what is needed to get started

README.md
Document installing Docker Desktop and setting required environment variables.
=> chore: add instructions to the README for running package tests

test/integration.test.js
=> fix: integration test to track store add in staging

.github/workflows/fetch-metrics-for-space.yaml, package-lock.json, package.json, tools/cli.js, tools/fetch-metrics-for-space.js, tools/package.json, tsconfig.json
Adds github action to query space metrics for given space
```
npm run fetch-metrics-for-space
> w3infra@0.0.0 fetch-metrics-for-space
> npm run fetch-metrics-for-space -w tools
> tools@1.0.0 fetch-metrics-for-space
> node cli.js fetch-metrics-for-space
Metrics found for provided space DID: 1
upload/add-total: 7
```
TODO
Closes #116
=> feat: github action to fetch metrics per space

ucan-invocation/constants.js, ucan-invocation/functions/metrics-store-add-size-total.js, ucan-invocation/functions/metrics-store-add-total.js, ucan-invocation/functions/metrics-store-remove-size-total.js, ucan-invocation/functions/metrics-store-remove-total.js, ucan-invocation/functions/metrics-upload-add-total.js, ucan-invocation/functions/metrics-upload-remove-total.js, ucan-invocation/functions/space-metrics-store-add-size-total.js, ucan-invocation/functions/space-metrics-store-add-total.js, ucan-invocation/functions/space-metrics-store-remove-size-total.js, ucan-invocation/functions/space-metrics-store-remove-total.js, ucan-invocation/functions/space-metrics-upload-add-total.js, ucan-invocation/functions/space-metrics-upload-remove-total.js, ucan-invocation/test/functions/metrics-store-add-size-total.test.js, ucan-invocation/test/functions/metrics-store-add-total.test.js, ucan-invocation/test/functions/metrics-store-remove-size-total.test.js, ucan-invocation/test/functions/metrics-store-remove-total.test.js, ucan-invocation/test/functions/metrics-upload-add-total.test.js, ucan-invocation/test/functions/metrics-upload-remove-total.test.js, ucan-invocation/test/functions/space-metrics-store-add-size-total.test.js, ucan-invocation/test/functions/space-metrics-store-add-total.test.js, ucan-invocation/test/functions/space-metrics-store-remove-size-total.test.js, ucan-invocation/test/functions/space-metrics-store-remove-total.test.js, ucan-invocation/test/functions/space-metrics-upload-add-total.test.js, ucan-invocation/test/functions/space-metrics-upload-remove-total.test.js, ucan-invocation/types.ts, upload-api/test/ucan-invocation.test.js, upload-api/ucan-invocation.js
=> fix: change kinesis stream type

docs/ucan-invocation-stream.md
=> docs: ucan invocation

tools/cli.js, tools/d1-migration/add-to-dynamo.js, tools/d1-migration/print-d1-emails.js, tools/d1-migration/verify-d1-dynamo-migration.js
grab data from D1 and use it to verify that all the bits got moved correctly
during the course of this I found a bug in the migration script - whew! thanks for the suggestion @vasco-santos
also add a simple utility to list the emails of folks who have registered for w3up
=> feat: add d1 -> dynamo migration verification script

.env.tpl, README.md, stacks/upload-api-stack.js, upload-api/functions/ucan-invocation-router.js, upload-api/functions/utils.js
My local env was not working and after digging through the dev deployment to find out what was going on, noticed that there were no docs for the Delegations Bucket, so added it now.
Also ended up adding a validation for the environment
=> fix: add needed env variables for local testing

stacks/ucan-invocation-stack.js
We promote staging to prod, so actually we would destroy this resource...
=> chore: keep kinesis historical stream in staging

billing/data/customer.js, billing/lib/api.ts, billing/tables/customer.js
Make customer store a getter and putter so that https://github.com/web3-storage/w3infra/pull/249 can get and update the customer.
=> feat: customer getter and putter

filecoin/functions/handle-cron-tick.js, stacks/filecoin-stack.js, stacks/upload-api-stack.js, test/filecoin.test.js
Using wrong CID invocation + missing did to match receipt CIDs
=> fix: filecoin accept receipt

package-lock.json, upload-api/tables/consumer.js
🤦 implementation was not updated to actually save this value to the DB.
=> fix: actually store the customer DID in the consumer table

upload-api/tables/delegations.js
This is used in `access/claim` and has been throwing errors when there are large numbers of delegations to claim. I think this is because we are fetching them serially, and am hoping that by fetching delegations concurrently we speed that up a lot.
=> feat: fetch delegations concurrently

test/filecoin.test.js
Depending on the aggregate buffering and timings in queue, MAY happen that not all pieces are needed to create the aggregate. If this is the case, there is a chance that one piece in the 4 uploaded will not make it to the aggregate, being still in queue for next one. In these integration tests, we just care that one Piece made it, so changed test to instead of expecting that first piece made it, we now do a race for all the pieces, and just expect one to make it
=> fix: filecoin integration tests more robust

filecoin/package.json, package-lock.json, upload-api/package.json
Bubble up https://github.com/web3-storage/w3up/pull/1191 to infra
=> fix: storefront events cron with max concurrency

.github/workflows/follow-filecoin-receipt-chain.yaml, package-lock.json, tools/cli.js, tools/follow-filecoin-receipt-chain.js, tools/package.json
Give it a Piece, and it will check where it is at in the pipeline
=> feat: tool for following filecoin receipt chain

filecoin/package.json, package-lock.json
=> fix: upgrade fr32-sha2-256-trunc-254-padded-binary-tree-multihash to 3.1.1

stacks/ucan-invocation-stack.js
See https://protocol-labs-it.sentry.io/issues/4707010165/?project=4504515009970176&project=4504253926539264&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1
looks like there is an issue with the CID in invocation nb fields https://protocol-labs-it.sentry.io/issues/4707010165/?project=4504515009970176&project=4504253926539264&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1
=> fix: disable filecoin metrics

package-lock.json, stacks/ucan-invocation-stack.js, ucan-invocation/filecoin.js, ucan-invocation/functions/metrics-aggregate-offer-and-accept-total.js, ucan-invocation/package.json, ucan-invocation/test/functions/metrics-aggregate-offer-total.test.js
And re-enable lambda after disabled it on https://github.com/web3-storage/w3infra/pull/304
See https://protocol-labs-it.sentry.io/issues/4707010165/?project=4504515009970176&project=4504253926539264&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1
=> fix: filecoin metrics decode

docs/ucan-invocation-stream.md
I think these need more work, but want to see how this lands.
=> chore: first pass at docs for the delivery firehose

upload-api/html.jsx
This is the same as https://github.com/web3-storage/w3infra/pull/331
=> fix: use same header when validating email

billing/functions/usage-table.js
Skips reporting usage for this space
=> feat: skip reporting usage for space temporarily

stacks/filecoin-stack.js
See https://protocol-labs-it.sentry.io/issues/5133113187/?project=4506587250819072&project=4504253926539264&project=4504515009970176&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=0
=> fix: increase piece compute timeout

upload-api/tables/store.js
Per https://github.com/web3-storage/w3up/pull/1344
=> feat!: remove issuer

stacks/upload-api-stack.js
Integration tests will make sure this does not happen when ready
=> fix: permissions for index add

stacks/ucan-invocation-stack.js, test/blob.test.js, test/integration.test.js
quick follow up from https://github.com/w3s-project/w3infra/pull/369
=> fix: add env vars to integration tests

.github/workflows/get-oldest-pieces-pending-deal.yml, tools/cli.js, tools/get-oldest-pieces-pending-deals.js, tools/package.json
Be able to query oldest pieces pending deals
=> feat: get oldest pieces pending deals tool

filecoin/functions/metrics-aggregate-offer-and-accept-total.js
This is a small perf tweak to update these filecoin metrics in parallel.
=> feat: update filecoin metrics in parallel

upload-api/stores/agent/stream.js
This PR adds a partition key to kinesis messages that allows consumers to consume messages in parallel using `parallelizationFactor`.
Context: We added `parallelizationFactor` but it had no effect. This is because we set the same partition key for every message.
=> feat: partition kinesis messages by task CID

package.json, upload-api/functions/validate-email.jsx, upload-api/html-storacha/index.jsx
https://github.com/storacha/w3infra/pull/425 was not caught because we're not linting `jsx` files.
I verified that this PR caught the error:
```
/Users/alan/Code/storacha/w3infra/upload-api/html-w3s/index.jsx
180:13  error  'preact' is not defined  no-undef
```
=> chore: lint jsx

upload-api/stores/agent/stream.js
we're seeing this error a LOT in production but don't have much information to debug from - add a bit more
=> feat: add debugging around production error

upload-api/functions/ucan-invocation-router.js
Temporary solution to resolve `did:web` from requests coming from other services, such as the Gateway (`did:web:staging.w3s.link` & `did:web:w3s.link`).
=> feat(upload-api): resolve did:web

billing/lib/ucan-stream.js
Add logging to aid in debugging the error in the Store Space Usage Delta (Staging env).
=> fix: debugging storeSpaceUsageDelta

upload-api/functions/sample.js
I missed this in my "disable everything" pass
=> feat: disable tracing for `sample.js`

package.json, pnpm-lock.yaml, pnpm-workspace.yaml, stacks/upload-api-stack.js, stacks/upload-db-stack.js, upload-api/external-services/router.js, upload-api/functions/ucan-invocation-router.js, upload-api/package.json, upload-api/tables/index.js, upload-api/tables/replica.js, upload-api/test/helpers/external-services/router.js, upload-api/test/helpers/external-services/storage-provider.js, upload-api/test/helpers/ucan.js
Implements the `replicaStore` and the interface addition to the router for selecting storage providers for replications. Wires everything up and runs the tests.
depends on https://github.com/storacha/upload-service/pull/253
=> feat: implement replication protocol

upload-api/functions/oauth-humanode-callback.js, upload-api/stores/humanodes.js, upload-api/tables/index.js, upload-api/types.ts
this will be helpful for administration
=> fix: associate storacha account ID with humanode subject

billing/test/utils/stripe.js, billing/utils/stripe.js
dramatically better handling of stripe webhooks, particularly in cases where a user previous signed up for the "no credit card tier" - previous in those cases the customer records would get overwritten.
now:
1) if a user is upgrading from the no-cc tier, we will preserve their existing customer record 
2) if a user is trying to change the stripe account associated with their customer id we'll throw an error 
3) if a user is trying to change the product associated with the stripe account we know is associated with their account, we'll do that
fixes https://github.com/storacha/ai-integrations/issues/55
=> fix: better handling for upgrade path from "no credit card" tier
